 ---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. Корзина будет хранится в сессии браузера
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Магазин будет SPA-приложение, которое не перезагружает страницу
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - Нужно разработать интерфейс интернет-магазина с просмотром и фильтрацией товаров, а также добавлением их в корзину
implicit:
  - В русской версии сайта названия категорий должны быть переведены на русский язык
  - У пользователя должна быть возможность подтвердить оформление заказа
  - В русской версии сайта цены должны быть переведены в рубли
  - У пользователей должна быть возможность оплатить заказ
